services:
  - type: web
    name: vaterindex
    env: docker
    repo: https://github.com/Vater-Inc/VaterIndex.git
    plan: starter
    healthCheckPath: /health
    disk:
      name: vaterindex-data
      mountPath: /vaterindex-data
      sizeGB: 1
    envVars:
      - key: TYPESENSE_API_KEY
        generateValue: true
      - key: TYPESENSE_DATA_DIR
        value: /vaterindex-data
      - key: TYPESENSE_ENABLE_CORS
        value: true
